Internal Server Error: /
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 115, in get
    self.object = self.get_object()
  File "/home/stephane/git/zegveld/zegveld/views.py", line 16, in get_object
    first = Project.objects.first()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 490, in first
    objects = list((self if self.ordered else self.order_by('pk'))[:1])
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'zegveld.data_project' doesn't exist")
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 115, in get
    self.object = self.get_object()
  File "/home/stephane/git/zegveld/zegveld/views.py", line 16, in get_object
    first = Project.objects.first()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 490, in first
    objects = list((self if self.ordered else self.order_by('pk'))[:1])
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'zegveld.data_project' doesn't exist")
Internal Server Error: /
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 115, in get
    self.object = self.get_object()
  File "/home/stephane/git/zegveld/zegveld/views.py", line 16, in get_object
    first = Project.objects.first()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 490, in first
    objects = list((self if self.ordered else self.order_by('pk'))[:1])
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'data_project.id' in 'field list'")
Internal Server Error: /
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 116, in get
    context = self.get_context_data(object=self.object)
  File "/home/stephane/git/zegveld/zegveld/views.py", line 20, in get_context_data
    context = super(HomeView, self).get_context_data(**kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 159, in get_context_data
    for loc in project.projectlocatie_set.all():
AttributeError: 'NoneType' object has no attribute 'projectlocatie_set'
Not Found: /admin
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Internal Server Error: /admin/auth/user/add/
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/auth/admin.py", line 121, in add_view
    extra_context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1467, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1078, in save_model
    obj.save()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1048, "Column 'last_login' cannot be null")
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/vic/perceel3/perceel-3/thumbnails/zegveld-perceel-3-n0/series/ammonium-n0.png
Not Found: /media/vic/perceel13/perceel-13/thumbnails/zegveld-perceel-13-n0/series/ammonium-n0.png
Not Found: /media/vic/perceel3/perceel-3/thumbnails/zegveld-perceel-3-n1/series/ammonium-n1.png
Not Found: /media/vic/perceel7/perceel-7/thumbnails/zegveld-perceel-7-n0/series/ammonium-n0.png
Not Found: /media/vic/perceel13/perceel-13/thumbnails/zegveld-perceel-13-n1/series/ammonium-n1.png
Not Found: /media/vic/perceel7/perceel-7/thumbnails/zegveld-perceel-7-n1/series/ammonium-n1.png
Not Found: /media/zegveld/1-perceel-3-vastlaag-waterpeil/perceel-3/thumbnails/zegveld-perceel-3-n0/series/bodemvocht-n0.png
Not Found: /media/vic/perceel13/perceel-13/thumbnails/zegveld-perceel-13-n0/series/bodemvocht-n0.png
Not Found: /media/vic/perceel7/perceel-7/thumbnails/zegveld-perceel-7-n0/series/bodemvocht-n0.png
Not Found: /media/vic/perceel3/perceel-3/thumbnails/zegveld-perceel-3-n1/series/bodemvocht-n1.png
Not Found: /media/vic/perceel13/perceel-13/thumbnails/zegveld-perceel-13-n1/series/bodemvocht-n1.png
Not Found: /media/zegveld/1-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/daily-precipitation-p3-ecrn-100.png
Not Found: /media/vic/perceel7/perceel-7/thumbnails/zegveld-perceel-7-n1/series/bodemvocht-n1.png
Not Found: /media/zegveld/1-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/ec-p1-ctd.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/ec-p1-ctd-10.png
Not Found: /media/zegveld/1-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/ec-p1-ctd.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/ec-p2-gs3.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/ec-p1-ctd-5.png
Not Found: /media/zegveld/1-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/ec-p2-gs3.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/ec-p2-gs3.png
Not Found: /media/zegveld/1-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/ec-p3-gs3.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/ec-p3-gs3.png
Not Found: /media/zegveld/1-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/ec-p4-ctd-10.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/ec-p4-ctd-10.png
Not Found: /media/zegveld/2-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/ec-p4-gs3.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/ec-p5-ctd-10.png
Not Found: /media/zegveld/1-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/ec-p5-ctd-10.png
Not Found: /media/vic/perceel3/perceel-3/thumbnails/zegveld-perceel-3-n0/series/fosfor-n0.png
Not Found: /media/vic/perceel13/perceel-13/thumbnails/zegveld-perceel-13-n0/series/fosfor-n0.png
Not Found: /media/vic/perceel7/perceel-7/thumbnails/zegveld-perceel-7-n0/series/fosfor-n0.png
Not Found: /media/vic/perceel3/perceel-3/thumbnails/zegveld-perceel-3-n1/series/fosfor-n1.png
Not Found: /media/vic/perceel13/perceel-13/thumbnails/zegveld-perceel-13-n1/series/fosfor-n1.png
Not Found: /media/vic/perceel7/perceel-7/thumbnails/zegveld-perceel-7-n1/series/fosfor-n1.png
Not Found: /media/thumbnails/series/378/gwst-perceel3.png
Not Found: /media/zegveld/1-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/level-p1-ctd.png
Not Found: /media/zegveld/1-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/level-p1-ctd.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/level-p1-ctd-10.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/level-p1-ctd-5.png
Not Found: /media/zegveld/1-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/level-p5-ctd-10.png
Not Found: /media/zegveld/2-perceel-7/perceel-7/thumbnails/regenradar-zegveld/series/neerslag.png
Not Found: /media/vic/perceel3/perceel-3/thumbnails/zegveld-perceel-3-n0/series/nitraat-n0.png
Not Found: /media/vic/perceel7/perceel-7/thumbnails/zegveld-perceel-7-n0/series/nitraat-n0.png
Not Found: /media/vic/perceel13/perceel-13/thumbnails/zegveld-perceel-13-n0/series/nitraat-n0.png
Not Found: /media/vic/perceel3/perceel-3/thumbnails/zegveld-perceel-3-n1/series/nitraat-n1.png
Not Found: /media/vic/perceel13/perceel-13/thumbnails/zegveld-perceel-13-n1/series/nitraat-n1.png
Not Found: /media/vic/perceel7/perceel-7/thumbnails/zegveld-perceel-7-n1/series/nitraat-n1.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/soilw100_200cm_mean.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/soilw100_200cm_std.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/soilw10_40cm_mean.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/soilw10_40cm_std.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/soilw40_100cm_mean.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/soilw40_100cm_std.png
Not Found: /media/zegveld/1-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/temp-p1-ctd.png
Not Found: /media/zegveld/1-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/temp-p1-ctd.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/temp-p1-ctd-10.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/temp-p1-ctd-5.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/temp-p2-gs3.png
Not Found: /media/zegveld/1-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/temp-p2-gs3.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/temp-p3-ectrt-1.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/temp-p2-gs3.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/temp-p3-ectrt-1.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/temp-p3-gs3.png
Not Found: /media/zegveld/1-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/temp-p3-gs3.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/temp-p4-ctd-10.png
Not Found: /media/zegveld/1-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/temp-p4-ctd-10.png
Not Found: /media/zegveld/1-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/temp-p4-ectrt-1.png
Not Found: /media/zegveld/2-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/temp-p4-gs3.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/temp-p5-ctd-10.png
Not Found: /media/zegveld/1-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/temp-p5-ctd-10.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/temp-p5-ectrt-1.png
Not Found: /media/thumbnails/series/383/tmp.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/temp-perceel-3.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/tsoil0_10cm_mean.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/tsoil0_10cm_std.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/tsoil100_200cm_mean.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/tsoil100_200cm_std.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/tsoil10_40cm_std.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/tsoil10_40cm_mean.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/tsoil40_100cm_mean.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/ensemble-bodem/series/tsoil40_100cm_std.png
Not Found: /media/zegveld/1-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/vwc-p2-gs3.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/vwc-p2-gs3.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/vwc-p3-gs3.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/vwc-p2-gs3.png
Not Found: /media/zegveld/1-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/vwc-p3-gs3.png
Not Found: /media/zegveld/2-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/vwc-p4-gs3.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/vwc2-p2-gs3.png
Not Found: /media/zegveld/1-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/vwc2-p2-gs3.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/vwc2-p2-gs3.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/vwc2-p3-gs3.png
Not Found: /media/zegveld/1-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/vwc2-p3-gs3.png
Not Found: /media/zegveld/2-perceel-7/perceel-7/thumbnails/zegveld-kastje-2/series/vwc2-p4-gs3.png
Not Found: /media/zegveld/1-perceel-3-vastlaag-waterpeil/perceel-3/thumbnails/zegveld-grondwaterstand-hm-p3/series/zegveld-grondwaterstand-hm-p3.png
Not Found: /media/zegveld/3-perceel-13/perceel-13/thumbnails/zegveld-kastje-3/series/zegveld-slootwaterpeil-perceel-13.png
Not Found: /media/zegveld/2-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/series/zegveld-slootwaterpeil-perceel-3.png
Internal Server Error: /admin/data/dashboard/add/
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1468, in changeform_view
    self.save_related(request, form, formsets, not add)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1102, in save_related
    self.save_formset(request, form, formset, change=change)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1090, in save_formset
    formset.save()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/forms/models.py", line 640, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/forms/models.py", line 771, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/forms/models.py", line 904, in save_new
    obj.save()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`zegveld`.`data_dashboardchart`, CONSTRAINT `chart_id_refs_id_8b7b64fe` FOREIGN KEY (`chart_id`) REFERENCES `data_chart` (`id`))')
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 394, in login
    return login(request, **defaults)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 57, in login
    current_site = get_current_site(request)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/sites/shortcuts.py", line 15, in get_current_site
    return Site.objects.get_current(request)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 60, in get_current
    return self._get_site_by_id(site_id)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 39, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'zegveld.django_site' doesn't exist")
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 57, in login
    current_site = get_current_site(request)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/sites/shortcuts.py", line 15, in get_current_site
    return Site.objects.get_current(request)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 60, in get_current
    return self._get_site_by_id(site_id)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 39, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'zegveld.django_site' doesn't exist")
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/
Not Found: /media/zegveld/perceel7/perceel-7/thumbnails/zegveld-kastje-2/parameter/ec-p1-ctd.png
Not Found: /media/zegveld/perceel7/perceel-7/thumbnails/zegveld-kastje-2/parameter/ec-p2-gs3.png
Not Found: /media/zegveld/1-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/parameter/ec-p3-gs3.png
Not Found: /media/zegveld/perceel7/perceel-7/thumbnails/zegveld-kastje-2/parameter/level-p1-ctd.png
Not Found: /media/zegveld/1-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/parameter/level-p4-ctd-10.png
Not Found: /media/zegveld/perceel7/perceel-7/thumbnails/zegveld-kastje-2/parameter/precipitation-p3-ecrn-100.png
Not Found: /media/zegveld/perceel7/perceel-7/thumbnails/zegveld-kastje-2/parameter/temp-p1-ctd.png
Not Found: /media/zegveld/perceel7/perceel-7/thumbnails/zegveld-kastje-2/parameter/temp-p2-gs3.png
Not Found: /media/zegveld/1-perceel-3/perceel-3/thumbnails/zegveld-kastje-1/parameter/temp-p3-gs3.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Internal Server Error: /
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/stephane/git/zegveld/zegveld/urls.py", line 15, in <module>
    url(r'^data/', include('acacia.data.urls',namespace='acacia')),
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/stephane/git/acaciadata/acacia/data/urls.py", line 21, in <module>
    url(r'^download/allereeksen/(?P<pk>\d+)', AllSeriesAsZip, name='all-series-zip'),
NameError: name 'AllSeriesAsZip' is not defined
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/stephane/git/zegveld/zegveld/urls.py", line 15, in <module>
    url(r'^data/', include('acacia.data.urls',namespace='acacia')),
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/stephane/git/acaciadata/acacia/data/urls.py", line 21, in <module>
    url(r'^download/allereeksen/(?P<pk>\d+)', AllSeriesAsZip, name='all-series-zip'),
NameError: name 'AllSeriesAsZip' is not defined
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/stephane/git/zegveld/zegveld/urls.py", line 15, in <module>
    url(r'^data/', include('acacia.data.urls',namespace='acacia')),
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/stephane/git/acaciadata/acacia/data/urls.py", line 21, in <module>
    url(r'^download/allereeksen/(?P<pk>\d+)', AllSeriesAsZip, name='all-series-zip'),
NameError: name 'AllSeriesAsZip' is not defined
Internal Server Error: /
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/stephane/git/zegveld/zegveld/urls.py", line 15, in <module>
    url(r'^data/', include('acacia.data.urls',namespace='acacia')),
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/stephane/git/acaciadata/acacia/data/urls.py", line 21, in <module>
    url(r'^download/allereeksen/(?P<pk>\d+)', AllSeriesAsZip, name='all-series-zip'),
NameError: name 'AllSeriesAsZip' is not defined
Internal Server Error: /
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader.py", line 64, in select_template
    return engine.get_template(template_name, dirs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 180, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
TemplateSyntaxError: 'block' tag with name 'content' appears more than once
Internal Server Error: /
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'all-series-zip' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'data/download/allereeksen/(?P<pk>\\d+)']
Internal Server Error: /data/download/allereeksen/45
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
Internal Server Error: /data/download/allereeksen/45
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'int' object has no attribute 'get'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'all-series-zip' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'data/download/allereeksen/(?P<pk>\\d+)']
Internal Server Error: /
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader.py", line 64, in select_template
    return engine.get_template(template_name, dirs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1458, in url
    args.append(parser.compile_filter(value))
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 639, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '-series-zip' from 'all-series-zip'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'all-series-zip' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'data/download/allereeksen/(?P<pk>\\d+)']
Internal Server Error: /
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'all-series-zip' with arguments '(u'zegveld',)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'data/download/allereeksen/(?P<pk>\\d+)']
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Internal Server Error: /data/download/allereeksen/1
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
Internal Server Error: /data/download/allereeksen/1
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'all-series-zip' with arguments '(u'zegveld',)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'data/download/allereeksen/(?P<pk>\\d+)']
Not Found: /data/download/allereeksen/45
Not Found: /data/download/allereeksen/131
Not Found: /data/download/allereeksen/131
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /data/download/allereeksen/131
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /data/download/allereeksen/65
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Internal Server Error: /data/download/allereeksen/65
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 20, in AllSeriesAsZip
    return series_as_zip(series)
TypeError: series_as_zip() takes exactly 2 arguments (1 given)
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Internal Server Error: /data/download/allereeksen/65
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 21, in AllSeriesAsZip
    return series_as_zip(series)
TypeError: series_as_zip() takes exactly 2 arguments (1 given)
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Internal Server Error: /data/download/allereeksen/65
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 21, in AllSeriesAsZip
    return all_series_as_zip(series, name)
  File "/home/stephane/git/acaciadata/acacia/data/util.py", line 121, in all_series_as_zip
    for f in s.series.all():
AttributeError: 'Series' object has no attribute 'series'
Internal Server Error: /data/download/allereeksen/65
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 21, in AllSeriesAsZip
    return all_series_as_zip(series, name)
  File "/home/stephane/git/acaciadata/acacia/data/util.py", line 121, in all_series_as_zip
    for f in s.series.all():
AttributeError: 'Series' object has no attribute 'series'
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Internal Server Error: /data/download/allereeksen/65
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 21, in AllSeriesAsZip
    return all_series_as_zip(series, name)
  File "/home/stephane/git/acaciadata/acacia/data/util.py", line 121, in all_series_as_zip
    filepath = s.filepath()
AttributeError: 'Series' object has no attribute 'filepath'
Internal Server Error: /data/download/allereeksen/65
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 21, in AllSeriesAsZip
    return all_series_as_zip(series, name)
  File "/home/stephane/git/acaciadata/acacia/data/util.py", line 123, in all_series_as_zip
    zf.write(file)
  File "/usr/lib/python2.7/zipfile.py", line 1123, in write
    st = os.stat(filename)
TypeError: coercing to Unicode: need string or buffer, HttpResponse found
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Internal Server Error: /data/download/allereeksen/65
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 21, in AllSeriesAsZip
    return all_series_as_zip(series, name)
  File "/home/stephane/git/acaciadata/acacia/data/util.py", line 123, in all_series_as_zip
    zf.write(file)
  File "/usr/lib/python2.7/zipfile.py", line 1123, in write
    st = os.stat(filename)
TypeError: coercing to Unicode: need string or buffer, HttpResponse found
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Internal Server Error: /data/download/allereeksen/65
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 21, in AllSeriesAsZip
    return all_series_as_zip(series, name)
  File "/home/stephane/git/acaciadata/acacia/data/util.py", line 123, in all_series_as_zip
    zf.write(file)
  File "/usr/lib/python2.7/zipfile.py", line 1123, in write
    st = os.stat(filename)
TypeError: coercing to Unicode: need string or buffer, HttpResponse found
Internal Server Error: /data/download/allereeksen/65
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 21, in AllSeriesAsZip
    return all_series_as_zip(series, name)
  File "/home/stephane/git/acaciadata/acacia/data/util.py", line 123, in all_series_as_zip
    zf.write(file)
  File "/usr/lib/python2.7/zipfile.py", line 1123, in write
    st = os.stat(filename)
TypeError: coercing to Unicode: need string or buffer, HttpResponse found
Internal Server Error: /data/download/allereeksen/65
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 21, in AllSeriesAsZip
    return all_series_as_zip(series, name)
  File "/home/stephane/git/acaciadata/acacia/data/util.py", line 124, in all_series_as_zip
    zf.write(file)
  File "/usr/lib/python2.7/zipfile.py", line 1123, in write
    st = os.stat(filename)
TypeError: coercing to Unicode: need string or buffer, instancemethod found
Internal Server Error: /data/download/allereeksen/65
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 21, in AllSeriesAsZip
    return all_series_as_zip(series, name)
  File "/home/stephane/git/acaciadata/acacia/data/util.py", line 124, in all_series_as_zip
    zf.write(file)
  File "/usr/lib/python2.7/zipfile.py", line 1123, in write
    st = os.stat(filename)
OSError: [Errno 2] No such file or directory: 'Datum/tijd,Ammonium-N0\n2014-04-30 12:00:00+00:00,259.2\n2014-05-07 12:00:00+00:00,229.2\n2014-05-14 12:00:00+00:00,172.6\n2014-05-21 12:00:00+00:00,196.2\n2014-05-28 12:00:00+00:00,193.9\n2014-06-04 12:00:00+00:00,144.3\n2014-06-11 12:00:00+00:00,206.8\n2014-06-18 12:00:00+00:00,268.7\n2014-06-25 12:00:00+00:00,369.7\n2014-07-02 12:00:00+00:00,175.7\n2014-07-09 12:00:00+00:00,218.6\n2014-07-16 12:00:00+00:00,237.7\n2014-07-23 12:00:00+00:00,159.9\n2014-07-30 12:00:00+00:00,116.1\n2014-08-06 12:00:00+00:00,294.0\n2014-08-13 12:00:00+00:00,101.6\n2014-08-20 12:00:00+00:00,560.6\n2014-08-27 12:00:00+00:00,120.5\n2014-09-03 12:00:00+00:00,2067.1\n2014-09-10 12:00:00+00:00,148.7\n2014-09-17 12:00:00+00:00,229.7\n2014-09-24 12:00:00+00:00,334.9\n2014-10-01 12:00:00+00:00,154.8\n2014-10-08 12:00:00+00:00,1204.0\n2014-10-15 12:00:00+00:00,191.6\n2014-10-22 12:00:00+00:00,123.4\n2014-10-29 12:00:00+00:00,123.4\n2014-11-12 12:00:00+00:00,360.4\n'
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Not Found: /media/images/zegveld/2-perceel-7-dynamisch-waterpeil/Gedraineerd dynamisch.png
Not Found: /media/images/zegveld/perceel3/Ongedraineerd laag.png
Not Found: /media/images/zegveld/3-perceel-13-vasthoog-waterpeil/Ongedraineerd hoog.png
Internal Server Error: /data/download/allereeksen/65
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 21, in AllSeriesAsZip
    return all_series_as_zip(series, name)
  File "/home/stephane/git/acaciadata/acacia/data/util.py", line 123, in all_series_as_zip
    series_name = s.name()
TypeError: 'unicode' object is not callable
Internal Server Error: /data/download/allereeksen/65
Traceback (most recent call last):
  File "/home/stephane/dj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stephane/git/acaciadata/acacia/data/views.py", line 21, in AllSeriesAsZip
    return all_series_as_zip(series, name)
  File "/home/stephane/git/acaciadata/acacia/data/util.py", line 122, in all_series_as_zip
    series_name = s.name()
TypeError: 'unicode' object is not callable
